# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateField(blank=True, db_index=True, null=True)),
                ('address', models.TextField()),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='carts.Cart')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='libraries.Library')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.DateField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('cart_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_line', to='carts.CartLine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='orders.Order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
